# Generated by Django 3.1 on 2021-08-12 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docrootcms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='element_id',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='uri',
            field=models.CharField(blank=True, max_length=700),
        ),
    ]
