# Generated by Django 3.2.6 on 2021-08-12 21:38
# Converts to BigAuto if not aleady done by customers and applies length limits
#   to handle mysql index to big issue
# NOTE: skipping a number since someone upgrading to django3+ may already have
#   made and ran migrations.  This will prevent a conflict if that occurred.
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docrootcms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='element_id',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='content',
            name='uri',
            field=models.CharField(blank=True, max_length=600),
        ),
    ]
